// Code generated by gocc; DO NOT EDIT.

package parser

import "github.com/uliseslugo/ilusa_pp/ast"

type (
	ProdTab      [numProductions]ProdTabEntry
	ProdTabEntry struct {
		String     string
		Id         string
		NTType     int
		Index      int
		NumSymbols int
		ReduceFunc func([]Attrib) (Attrib, error)
	}
	Attrib interface {
	}
)

var productionsTable = ProdTab{
	ProdTabEntry{
		String: `S' : P	<<  >>`,
		Id:         "S'",
		NTType:     0,
		Index:      0,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `P : "Program" id ":" P1 P2 P3 B	<< ast.NewProgram(X[1]) >>`,
		Id:         "P",
		NTType:     1,
		Index:      1,
		NumSymbols: 7,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewProgram(X[1])
		},
	},
	ProdTabEntry{
		String: `P1 : empty	<<  >>`,
		Id:         "P1",
		NTType:     2,
		Index:      2,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `P1 : CL	<<  >>`,
		Id:         "P1",
		NTType:     2,
		Index:      3,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `P2 : empty	<<  >>`,
		Id:         "P2",
		NTType:     3,
		Index:      4,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `P2 : DV	<<  >>`,
		Id:         "P2",
		NTType:     3,
		Index:      5,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `P3 : empty	<<  >>`,
		Id:         "P3",
		NTType:     4,
		Index:      6,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `P3 : F	<<  >>`,
		Id:         "P3",
		NTType:     4,
		Index:      7,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `B : "main" "(" ")" "{" B1 "}"	<<  >>`,
		Id:         "B",
		NTType:     5,
		Index:      8,
		NumSymbols: 6,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `B1 : empty	<<  >>`,
		Id:         "B1",
		NTType:     6,
		Index:      9,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `B1 : EST B1	<<  >>`,
		Id:         "B1",
		NTType:     6,
		Index:      10,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `CL : "Class" id ":" INH "{" "atributes" "{" ATR_CL "}" MET_CL "}"	<<  >>`,
		Id:         "CL",
		NTType:     7,
		Index:      11,
		NumSymbols: 11,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `INH : empty	<<  >>`,
		Id:         "INH",
		NTType:     8,
		Index:      12,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `INH : "inherits" id	<<  >>`,
		Id:         "INH",
		NTType:     8,
		Index:      13,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `MET_CL : empty	<<  >>`,
		Id:         "MET_CL",
		NTType:     9,
		Index:      14,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `MET_CL : "methods" "{" F MET_CL1 "}"	<<  >>`,
		Id:         "MET_CL",
		NTType:     9,
		Index:      15,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `MET_CL1 : empty	<<  >>`,
		Id:         "MET_CL1",
		NTType:     10,
		Index:      16,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `MET_CL1 : F MET_CL1	<<  >>`,
		Id:         "MET_CL1",
		NTType:     10,
		Index:      17,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `ATR_CL : "public" ":" ATR_SIMP "private" ":" ATR_SIMP "protected" ":" ATR_SIMP	<<  >>`,
		Id:         "ATR_CL",
		NTType:     11,
		Index:      18,
		NumSymbols: 9,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `ATR_SIMP : TIP_SIMP id DV2 ";" ATR_SIMP1	<<  >>`,
		Id:         "ATR_SIMP",
		NTType:     12,
		Index:      19,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `ATR_SIMP1 : empty	<<  >>`,
		Id:         "ATR_SIMP1",
		NTType:     13,
		Index:      20,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `ATR_SIMP1 : ATR_SIMP ATR_SIMP1	<<  >>`,
		Id:         "ATR_SIMP1",
		NTType:     13,
		Index:      21,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `DV : "variables" "{" DV1 ";" "}"	<<  >>`,
		Id:         "DV",
		NTType:     14,
		Index:      22,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `DV1 : TIP_COMP id DV2	<<  >>`,
		Id:         "DV1",
		NTType:     15,
		Index:      23,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `DV1 : TIP_SIMP id DV3 DV3 DV4	<<  >>`,
		Id:         "DV1",
		NTType:     15,
		Index:      24,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `DV2 : empty	<<  >>`,
		Id:         "DV2",
		NTType:     16,
		Index:      25,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `DV2 : "," id DV2	<<  >>`,
		Id:         "DV2",
		NTType:     16,
		Index:      26,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `DV3 : empty	<<  >>`,
		Id:         "DV3",
		NTType:     17,
		Index:      27,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `DV3 : "[" cte_i "]"	<<  >>`,
		Id:         "DV3",
		NTType:     17,
		Index:      28,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `DV4 : empty	<<  >>`,
		Id:         "DV4",
		NTType:     18,
		Index:      29,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `DV4 : "," id DV3 DV3 DV4	<<  >>`,
		Id:         "DV4",
		NTType:     18,
		Index:      30,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `TIP_SIMP : "int"	<<  >>`,
		Id:         "TIP_SIMP",
		NTType:     19,
		Index:      31,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `TIP_SIMP : "char"	<<  >>`,
		Id:         "TIP_SIMP",
		NTType:     19,
		Index:      32,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `TIP_SIMP : "float"	<<  >>`,
		Id:         "TIP_SIMP",
		NTType:     19,
		Index:      33,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `TIP_COMP : id	<<  >>`,
		Id:         "TIP_COMP",
		NTType:     20,
		Index:      34,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `F : "function" F1 id "(" F2 ")" "{" DV "}" "body" "{" EST B1 "}" "}"	<<  >>`,
		Id:         "F",
		NTType:     21,
		Index:      35,
		NumSymbols: 15,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `F1 : TIP_SIMP	<<  >>`,
		Id:         "F1",
		NTType:     22,
		Index:      36,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `F1 : "void"	<<  >>`,
		Id:         "F1",
		NTType:     22,
		Index:      37,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `F2 : empty	<<  >>`,
		Id:         "F2",
		NTType:     23,
		Index:      38,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `F2 : TIP_SIMP id F3	<<  >>`,
		Id:         "F2",
		NTType:     23,
		Index:      39,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `F3 : empty	<<  >>`,
		Id:         "F3",
		NTType:     24,
		Index:      40,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `F3 : "," TIP_SIMP id F3	<<  >>`,
		Id:         "F3",
		NTType:     24,
		Index:      41,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `EST : AS	<<  >>`,
		Id:         "EST",
		NTType:     25,
		Index:      42,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `EST : DEC	<<  >>`,
		Id:         "EST",
		NTType:     25,
		Index:      43,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `EST : ESC	<<  >>`,
		Id:         "EST",
		NTType:     25,
		Index:      44,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `EST : LEC	<<  >>`,
		Id:         "EST",
		NTType:     25,
		Index:      45,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `EST : LLAM	<<  >>`,
		Id:         "EST",
		NTType:     25,
		Index:      46,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `EST : RET	<<  >>`,
		Id:         "EST",
		NTType:     25,
		Index:      47,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `EST : REP	<<  >>`,
		Id:         "EST",
		NTType:     25,
		Index:      48,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `AS : id "=" H_EXP ";"	<<  >>`,
		Id:         "AS",
		NTType:     26,
		Index:      49,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `LLAM : id "(" LLAM1 ")"	<<  >>`,
		Id:         "LLAM",
		NTType:     27,
		Index:      50,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `LLAM1 : empty	<<  >>`,
		Id:         "LLAM1",
		NTType:     28,
		Index:      51,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `LLAM1 : H_EXP LLAM2	<<  >>`,
		Id:         "LLAM1",
		NTType:     28,
		Index:      52,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `LLAM2 : empty	<<  >>`,
		Id:         "LLAM2",
		NTType:     29,
		Index:      53,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `LLAM2 : "," H_EXP LLAM2	<<  >>`,
		Id:         "LLAM2",
		NTType:     29,
		Index:      54,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `RET : "return" "(" H_EXP ")"	<<  >>`,
		Id:         "RET",
		NTType:     30,
		Index:      55,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `LEC : "input" "(" VAR LEC1 ")"	<<  >>`,
		Id:         "LEC",
		NTType:     31,
		Index:      56,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `LEC1 : empty	<<  >>`,
		Id:         "LEC1",
		NTType:     32,
		Index:      57,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `LEC1 : "," VAR LEC1	<<  >>`,
		Id:         "LEC1",
		NTType:     32,
		Index:      58,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `ESC : "output" "(" ESC1 ESC2 ")" ";"	<<  >>`,
		Id:         "ESC",
		NTType:     33,
		Index:      59,
		NumSymbols: 6,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `ESC1 : H_EXP	<<  >>`,
		Id:         "ESC1",
		NTType:     34,
		Index:      60,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `ESC1 : cte_string	<<  >>`,
		Id:         "ESC1",
		NTType:     34,
		Index:      61,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `ESC2 : empty	<<  >>`,
		Id:         "ESC2",
		NTType:     35,
		Index:      62,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `ESC2 : "," ESC1 ESC2	<<  >>`,
		Id:         "ESC2",
		NTType:     35,
		Index:      63,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `DEC : "if" "(" H_EXP ")" "{" EST B1 "}" DEC1	<<  >>`,
		Id:         "DEC",
		NTType:     36,
		Index:      64,
		NumSymbols: 9,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `DEC1 : empty	<<  >>`,
		Id:         "DEC1",
		NTType:     37,
		Index:      65,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `DEC1 : "else" "{" EST B1 "}"	<<  >>`,
		Id:         "DEC1",
		NTType:     37,
		Index:      66,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `REP : "while" "(" H_EXP REP1	<<  >>`,
		Id:         "REP",
		NTType:     38,
		Index:      67,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `REP : "for" "(" AS ";" H_EXP ";" H_EXP REP1	<<  >>`,
		Id:         "REP",
		NTType:     38,
		Index:      68,
		NumSymbols: 8,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `REP1 : ")" "{" EST B1 "}"	<<  >>`,
		Id:         "REP1",
		NTType:     39,
		Index:      69,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `VAR : id VAR1 VAR1	<<  >>`,
		Id:         "VAR",
		NTType:     40,
		Index:      70,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `VAR1 : empty	<<  >>`,
		Id:         "VAR1",
		NTType:     41,
		Index:      71,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `VAR1 : "[" H_EXP "]"	<<  >>`,
		Id:         "VAR1",
		NTType:     41,
		Index:      72,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `H_EXP : S_EXP H_EXP1	<<  >>`,
		Id:         "H_EXP",
		NTType:     42,
		Index:      73,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `H_EXP1 : empty	<<  >>`,
		Id:         "H_EXP1",
		NTType:     43,
		Index:      74,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `H_EXP1 : LOG S_EXP	<<  >>`,
		Id:         "H_EXP1",
		NTType:     43,
		Index:      75,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `S_EXP : EXP S_EXP1	<<  >>`,
		Id:         "S_EXP",
		NTType:     44,
		Index:      76,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `S_EXP1 : empty	<<  >>`,
		Id:         "S_EXP1",
		NTType:     45,
		Index:      77,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `S_EXP1 : REL EXP	<<  >>`,
		Id:         "S_EXP1",
		NTType:     45,
		Index:      78,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `EXP : TERM EXP1	<<  >>`,
		Id:         "EXP",
		NTType:     46,
		Index:      79,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `EXP1 : empty	<<  >>`,
		Id:         "EXP1",
		NTType:     47,
		Index:      80,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `EXP1 : "+" EXP	<<  >>`,
		Id:         "EXP1",
		NTType:     47,
		Index:      81,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `EXP1 : "-" EXP	<<  >>`,
		Id:         "EXP1",
		NTType:     47,
		Index:      82,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `TERM : FAC TERM1	<<  >>`,
		Id:         "TERM",
		NTType:     48,
		Index:      83,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `TERM1 : empty	<<  >>`,
		Id:         "TERM1",
		NTType:     49,
		Index:      84,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `TERM1 : "*" TERM	<<  >>`,
		Id:         "TERM1",
		NTType:     49,
		Index:      85,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `TERM1 : "/" TERM	<<  >>`,
		Id:         "TERM1",
		NTType:     49,
		Index:      86,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `FAC : "(" H_EXP ")"	<<  >>`,
		Id:         "FAC",
		NTType:     50,
		Index:      87,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `FAC : VAR_CTE	<<  >>`,
		Id:         "FAC",
		NTType:     50,
		Index:      88,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `FAC : "+" VAR_CTE	<<  >>`,
		Id:         "FAC",
		NTType:     50,
		Index:      89,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `FAC : "-" VAR_CTE	<<  >>`,
		Id:         "FAC",
		NTType:     50,
		Index:      90,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `VAR_CTE : id	<<  >>`,
		Id:         "VAR_CTE",
		NTType:     51,
		Index:      91,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `VAR_CTE : cte_i	<<  >>`,
		Id:         "VAR_CTE",
		NTType:     51,
		Index:      92,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `VAR_CTE : cte_float	<<  >>`,
		Id:         "VAR_CTE",
		NTType:     51,
		Index:      93,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `LOG : "&&"	<<  >>`,
		Id:         "LOG",
		NTType:     52,
		Index:      94,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `LOG : "||"	<<  >>`,
		Id:         "LOG",
		NTType:     52,
		Index:      95,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `LOG : "!="	<<  >>`,
		Id:         "LOG",
		NTType:     52,
		Index:      96,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `REL : "<"	<<  >>`,
		Id:         "REL",
		NTType:     53,
		Index:      97,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `REL : ">"	<<  >>`,
		Id:         "REL",
		NTType:     53,
		Index:      98,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `REL : ">="	<<  >>`,
		Id:         "REL",
		NTType:     53,
		Index:      99,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `REL : "<="	<<  >>`,
		Id:         "REL",
		NTType:     53,
		Index:      100,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `REL : "=="	<<  >>`,
		Id:         "REL",
		NTType:     53,
		Index:      101,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
}
